# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{behave}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Matthew Gibbons"]
  s.date = %q{2010-04-06}
  s.description = %q{Behave is a Ruby Gem that encapsulates a number of commen model behaviors. }
  s.email = %q{mhgibbons@me.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/behave.rb",
     "lib/behave/reportable.rb",
     "spec/behave_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/accuser/behave}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Encapsulates common model behaviors}
  s.test_files = [
    "spec/behave_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activemodel>, [">= 3.0.0.beta2"])
      s.add_runtime_dependency(%q<activesupport>, [">= 3.0.0.beta2"])
      s.add_runtime_dependency(%q<mongoid>, [">= 2.0.0.beta2"])
      s.add_development_dependency(%q<rspec>, [">= 2.0.0.beta.4"])
    else
      s.add_dependency(%q<activemodel>, [">= 3.0.0.beta2"])
      s.add_dependency(%q<activesupport>, [">= 3.0.0.beta2"])
      s.add_dependency(%q<mongoid>, [">= 2.0.0.beta2"])
      s.add_dependency(%q<rspec>, [">= 2.0.0.beta.4"])
    end
  else
    s.add_dependency(%q<activemodel>, [">= 3.0.0.beta2"])
    s.add_dependency(%q<activesupport>, [">= 3.0.0.beta2"])
    s.add_dependency(%q<mongoid>, [">= 2.0.0.beta2"])
    s.add_dependency(%q<rspec>, [">= 2.0.0.beta.4"])
  end
end

