# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{behave}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Matthew Gibbons"]
  s.date = %q{2010-04-08}
  s.description = %q{Behave is a Ruby Gem that encapsulates a number of commen model behaviors.}
  s.email = %q{mhgibbons@me.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "behave.gemspec",
     "lib/behave.rb",
     "lib/behave/cachable.rb",
     "lib/behave/containable.rb",
     "lib/behave/lockable.rb",
     "lib/behave/moderatable.rb",
     "lib/behave/publishable.rb",
     "lib/behave/reportable.rb",
     "lib/behave/searchable.rb",
     "lib/behave/serializable.rb",
     "lib/behave/textilize.rb",
     "lib/behave/timestamp.rb",
     "lib/behave/versionable.rb",
     "lib/cached_document.rb",
     "spec/rcov.opts",
     "spec/spec.opts",
     "spec/spec_helper.rb",
     "spec/unit/behave/cachable_spec.rb",
     "spec/unit/behave/lockable_spec.rb",
     "spec/unit/behave/publishable_spec.rb",
     "spec/unit/behave/reportable_spec.rb"
  ]
  s.homepage = %q{http://github.com/accuser/behave}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Encapsulates common model behaviors}
  s.test_files = [
    "spec/spec_helper.rb",
     "spec/unit/behave/cachable_spec.rb",
     "spec/unit/behave/containable_spec.rb",
     "spec/unit/behave/lockable_spec.rb",
     "spec/unit/behave/publishable_spec.rb",
     "spec/unit/behave/reportable_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activemodel>, [">= 3.0.0.beta2"])
      s.add_runtime_dependency(%q<activesupport>, [">= 3.0.0.beta2"])
      s.add_runtime_dependency(%q<delayed_job>, [">= 1.7.0"])
      s.add_runtime_dependency(%q<mongoid>, [">= 2.0.0.beta2"])
      s.add_runtime_dependency(%q<mongoid_cached_document>, [">= 0.1.0"])
      s.add_runtime_dependency(%q<nokogiri>, [">= 1.4.0"])
      s.add_runtime_dependency(%q<RedCloth>, [">= 4.2.0"])
      s.add_runtime_dependency(%q<sunspot_rails>, [">= 1.0.0"])
    else
      s.add_dependency(%q<activemodel>, [">= 3.0.0.beta2"])
      s.add_dependency(%q<activesupport>, [">= 3.0.0.beta2"])
      s.add_dependency(%q<delayed_job>, [">= 1.7.0"])
      s.add_dependency(%q<mongoid>, [">= 2.0.0.beta2"])
      s.add_dependency(%q<mongoid_cached_document>, [">= 0.1.0"])
      s.add_dependency(%q<nokogiri>, [">= 1.4.0"])
      s.add_dependency(%q<RedCloth>, [">= 4.2.0"])
      s.add_dependency(%q<sunspot_rails>, [">= 1.0.0"])
    end
  else
    s.add_dependency(%q<activemodel>, [">= 3.0.0.beta2"])
    s.add_dependency(%q<activesupport>, [">= 3.0.0.beta2"])
    s.add_dependency(%q<delayed_job>, [">= 1.7.0"])
    s.add_dependency(%q<mongoid>, [">= 2.0.0.beta2"])
    s.add_dependency(%q<mongoid_cached_document>, [">= 0.1.0"])
    s.add_dependency(%q<nokogiri>, [">= 1.4.0"])
    s.add_dependency(%q<RedCloth>, [">= 4.2.0"])
    s.add_dependency(%q<sunspot_rails>, [">= 1.0.0"])
  end
end

